import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium, expect } from '@playwright/test';
import { setup, signIn, BASE_URL } from '../helpers/harness.ts';

test('Excel clipboard becomes an editable table, prefers HTML over image and survives Done/reload', async () => {
  const fx = await setup();
  let browser;
  try {
    const jar = await signIn(fx.admin.email, fx.admin.password);
    const post = async (url: string, body: unknown) => {
      const res = await fetch(`${BASE_URL}${url}`, { method: 'POST', headers: { cookie: jar.header, 'content-type': 'application/json' }, body: JSON.stringify(body) });
      assert.equal(res.status, 200, await res.clone().text()); return res.json();
    };
    const doc = await post(`/api/projects/${fx.projectId}/docs`, { title: 'Excel paste check' });
    const record = await post(`/api/docs/${doc.id}/pages`, { title: 'Spreadsheet table' });
    const { rows } = await fx.client.query('SELECT project_slug FROM pmt_projects WHERE project_id=$1', [fx.projectId]);
    browser = await chromium.launch({ channel: 'msedge', headless: true });
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    await context.addCookies(jar.header.split('; ').map(pair => { const at=pair.indexOf('='); return { name: pair.slice(0,at), value: pair.slice(at+1), url: BASE_URL }; }));
    const page = await context.newPage();
    const uploads: string[] = [];
    page.on('request', request => { if (request.method() === 'POST' && request.url().includes('/doc-assets')) uploads.push(request.url()); });
    await page.goto(`${BASE_URL}/p/${rows[0].project_slug}/docs/${record.slug}?edit=1`);
    const editor = page.getByRole('textbox', { name: 'Content', exact: true });
    await expect(editor).toBeVisible();
    const paste = async (text: string, html = '', preview = false) => editor.evaluate((el, clipboard) => {
      const data = new DataTransfer(); data.setData('text/plain', clipboard.text);
      if (clipboard.html) data.setData('text/html', clipboard.html);
      if (clipboard.preview) data.items.add(new File([new Uint8Array([137,80,78,71,13,10,26,10])], 'excel-preview.png', { type: 'image/png' }));
      el.dispatchEvent(new ClipboardEvent('paste', { clipboardData: data, bubbles: true, cancelable: true }));
    }, { text, html, preview });
    await editor.click();
    await paste('รหัส\tจำนวน\tหมายเหตุ\r\n0012\t1,234.50\t\r\n"สอง\nบรรทัด"\t"พูดว่า ""ใช่"""\tครบ\r\n');
    await expect(editor.locator('table')).toHaveCount(1);
    await expect(editor.locator('tr')).toHaveCount(3);
    await expect(editor.locator('tr').nth(1).locator('td')).toHaveText(['0012', '1,234.50', '']);
    await expect(editor.locator('tr').nth(2).locator('td').first().locator('p')).toHaveText(['สอง', 'บรรทัด']);
    // Paste a range inside an existing cell; no nested table is introduced.
    await editor.locator('td').first().click();
    await editor.press('Control+Home');
    await paste('ชื่อ\tค่า\r\nA\t02');
    await expect(editor.locator('table')).toHaveCount(1);
    await expect(editor.locator('tr').first().locator('td').first()).toHaveText('ชื่อ');
    await expect(editor.locator('tr').nth(1).locator('td').nth(1)).toHaveText('02');
    await editor.press('Control+a'); await editor.press('Backspace');
    await paste('หัวตาราง\t\tราคา\nสินค้า\tจำนวน\t001\n\tเพิ่มเติม\t002', '<html xmlns:x="urn:schemas-microsoft-com:office:excel"><body><!--StartFragment--><table><tr><td colspan="2"><b>หัวตาราง</b></td><td>ราคา</td></tr><tr><td rowspan="2">สินค้า</td><td>จำนวน</td><td>001</td></tr><tr><td>เพิ่มเติม</td><td>002</td></tr></table><!--EndFragment--></body></html>', true);
    await expect(editor.locator('table')).toHaveCount(1);
    await expect(editor.locator('td[colspan="2"]')).toHaveText('หัวตาราง');
    await expect(editor.locator('td[rowspan="2"]')).toHaveText('สินค้า');
    await expect(editor.locator('strong')).toHaveText('หัวตาราง');
    assert.deepEqual(uploads, []);
    await expect(editor.locator('img')).toHaveCount(0);
    await editor.locator('tr').nth(1).locator('td').nth(1).fill('แก้ไขได้');
    await editor.locator('tr').nth(1).locator('td').nth(1).click();
    await page.getByLabel('Table fill color').fill('#dceaff');
    await page.getByRole('button', { name: 'Row color', exact: true }).click();
    for (const cell of await editor.locator('tr').nth(1).locator('td').all()) await expect(cell).toHaveCSS('background-color', 'rgb(220, 234, 255)');
    await page.getByLabel('Table fill color').fill('#fff0b3');
    await page.getByRole('button', { name: 'Column color', exact: true }).click();
    await expect(editor.locator('td[colspan="2"]')).toHaveCSS('background-color', 'rgb(255, 240, 179)');
    await expect(editor.locator('tr').nth(2).locator('td').first()).toHaveCSS('background-color', 'rgb(255, 240, 179)');
    await page.getByRole('button', { name: 'Clear column color', exact: true }).click();
    await expect(editor.locator('td[colspan="2"]')).not.toHaveAttribute('style', /background-color/);
    await page.getByRole('button', { name: 'Column color', exact: true }).click();
    await page.screenshot({ path: 'data/doc-excel-paste-desktop.png' });
    const controlsBox = await page.getByRole('group', { name: 'Table actions', exact: true }).boundingBox();
    const tableBox = await editor.locator('table').boundingBox();
    assert.ok(controlsBox && tableBox && controlsBox.y + controlsBox.height <= tableBox.y + 1, 'Table settings sit above the selected table');
    await page.getByRole('button', { name: 'Done editing', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Edit page', exact: true })).toBeEnabled();
    await page.reload();
    await expect(page.locator('article table')).toHaveCount(1);
    await expect(page.locator('article td[rowspan="2"]')).toHaveText('สินค้า');
    await expect(page.locator('article')).toContainText('แก้ไขได้');
    await expect(page.locator('article .doc-table-config-anchor')).toHaveCount(0);
    await expect(page.locator('article td[colspan="2"]')).toHaveCSS('background-color', 'rgb(255, 240, 179)');
    await expect(page.locator('article td[rowspan="2"]')).toHaveCSS('background-color', 'rgb(220, 234, 255)');
    await page.setViewportSize({ width: 390, height: 844 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
    await page.screenshot({ path: 'data/doc-excel-paste-mobile.png' });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.getByRole('button', { name: 'Edit page', exact: true }).click();
    await expect(editor).toBeVisible();
    await editor.locator('td').first().click();
    await page.getByRole('button', { name: 'Header row', exact: true }).click();
    await expect(editor.locator('tr').first().locator('th')).toHaveCount(2);
    await page.getByRole('group', { name: 'Filter columns', exact: true }).getByRole('checkbox', { name: 'ราคา', exact: true }).check();
    await page.getByRole('button', { name: 'Done editing', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Edit page', exact: true })).toBeEnabled();
    await page.reload();
    const filter = page.locator('summary[aria-label="Filter ราคา"]');
    await expect(filter).toBeVisible();
    await expect(page.locator('.doc-table-filter-menu')).toHaveCount(1);
    await filter.click();
    const choices = page.getByRole('group', { name: 'Values for ราคา', exact: true });
    await choices.getByRole('button', { name: 'Clear selection', exact: true }).click();
    await choices.getByRole('checkbox', { name: '001', exact: true }).check();
    // The vertical merge keeps its two-row group intact.
    await expect(page.locator('article tbody tr')).toHaveCount(2);
    await choices.getByRole('checkbox', { name: '002', exact: true }).check();
    await expect(choices.getByRole('checkbox', { name: '001', exact: true })).toBeChecked();
    await expect(choices.getByRole('checkbox', { name: '002', exact: true })).toBeChecked();
    await choices.getByRole('button', { name: 'Clear selection', exact: true }).click();
    await expect(page.locator('article tbody tr')).toHaveCount(0);
    await expect(page.getByRole('status')).toContainText('No matching rows');
    await page.getByRole('button', { name: 'Clear filters', exact: true }).click();
    await expect(page.locator('article tbody tr')).toHaveCount(2);
    await page.screenshot({ path: 'data/doc-table-filter-desktop.png' });
  } finally { await browser?.close(); await fx.cleanup(); }
});
