const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require('C:/Users/ouan-dev/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
const server=spawn(process.execPath,['server.cjs'],{env:{...process.env,PORT:'4187'},windowsHide:true,stdio:'pipe'});let browser;
(async()=>{
 await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.stderr.once('data',d=>reject(new Error(d.toString())));server.once('error',reject);server.once('exit',code=>reject(new Error('Server exited '+code)));});
 browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const base='http://localhost:4187/';await page.goto(base+'#visitors/registered');
 const ids=await page.locator('[data-id^="REGISTER-DEMO-"]').evaluateAll(nodes=>nodes.map(n=>n.dataset.id).sort());assert.equal(ids.length,5);
 for(const tab of ['visitors','visitors/registered']){await page.goto(base+'#'+tab);assert.equal(await page.getByRole('button',{name:'เรียกยาม',exact:true}).count(),0);const dates=await page.locator('#visitor-list .visit-row').evaluateAll(nodes=>{const data=JSON.parse(localStorage.getItem('bannayuu.resident.v1'));return nodes.map(n=>data.visitors.find(v=>v.id===n.dataset.id).start);});assert.deepEqual(dates,[...dates].sort().reverse());const first=page.locator('#visitor-list .visit-row').first();const plate=await first.getAttribute('data-plate');await page.getByLabel('ค้นหาทะเบียนรถ').fill(plate.replace(/\s/g,''));assert(await first.isVisible());await page.getByLabel('ค้นหาทะเบียนรถ').fill('ไม่มีทะเบียนนี้');assert.equal(await page.locator('#visitor-list .visit-row:visible').count(),0);assert(await page.locator('#visitor-filter-empty').isVisible());await page.getByLabel('ค้นหาทะเบียนรถ').fill('');assert.equal(await page.locator('#visitor-list .visit-row:visible').count(),dates.length);}
 const labels=['รอเข้า','รอประทับตรา','ออกแล้ว','ยกเลิก','หมดอายุ'];
 await page.goto(base+'#visitors/registered');await page.evaluate(()=>{document.querySelector('#visitor-status-panel').hidden=false;});const statusColors=await page.evaluate(()=>[...document.querySelectorAll('[data-visitor-status]')].map(input=>{const row=[...document.querySelectorAll('.visit-row')].find(row=>row.dataset.status===input.value),pill=row.querySelector('.pill'),label=input.closest('label'),before=getComputedStyle(label);const result={status:input.value,pillColor:getComputedStyle(pill).color,pillBackground:getComputedStyle(pill).backgroundColor,color:before.color,background:before.backgroundColor};input.checked=true;result.selectedColor=getComputedStyle(label).color;result.selectedBackground=getComputedStyle(label).backgroundColor;input.checked=false;return result;}));for(const c of statusColors){assert.equal(c.color,c.pillColor,c.status);assert.equal(c.background,c.pillBackground,c.status);assert.equal(c.selectedColor,c.pillColor,c.status);assert.equal(c.selectedBackground,c.pillBackground,c.status);}await page.reload();
 await page.goto(base+'#visitors/registered');assert(await page.locator('#visitor-status-panel').isHidden());if(await page.locator('[data-action="guard-dismiss"]:visible').count())await page.locator('[data-action="guard-dismiss"]:visible').click();await page.getByRole('button',{name:'กรองสถานะ',exact:true}).click();assert(await page.locator('#visitor-status-panel').isVisible());await page.locator('[data-visitor-status][value="รอเข้า"]').check();await page.locator('[data-visitor-status][value="รอประทับตรา"]').check();assert.equal(await page.locator('.visitor-filter-count,[data-status-count]').count(),0);await page.locator('[data-action="visitor-filter-toggle"]').click();assert(await page.locator('#visitor-status-panel').isHidden());assert.equal(await page.locator('[data-visitor-status]:checked').count(),2);await page.locator('[data-action="visitor-filter-toggle"]').click();let filtered=await page.locator('#visitor-list .visit-row:visible').evaluateAll(nodes=>nodes.map(n=>n.dataset.status));assert(filtered.includes('รอเข้า')&&filtered.includes('รอประทับตรา'));assert(filtered.every(s=>['รอเข้า','รอประทับตรา'].includes(s)));
 await page.getByLabel('ค้นหาทะเบียนรถ').fill('ขก2302');assert.equal(await page.locator('#visitor-list .visit-row:visible').count(),1);await page.locator('[data-visitor-status][value="รอประทับตรา"]').uncheck();assert.equal(await page.locator('#visitor-list .visit-row:visible').count(),0);await page.locator('[data-visitor-status][value="รอเข้า"]').uncheck();assert.equal(await page.locator('#visitor-list .visit-row:visible').count(),1);await page.getByLabel('ค้นหาทะเบียนรถ').fill('');assert((await page.locator('#visitor-list .visit-row:visible').count())>=5);
 await page.locator('[data-visitor-status][value="รอเข้า"]').check();await page.getByLabel('ค้นหาทะเบียนรถ').fill('ขก2302');assert(await page.locator('#visitor-filter-empty').isVisible());await page.locator('[data-action="visitor-status-clear"]').click();assert.equal(await page.getByLabel('ค้นหาทะเบียนรถ').inputValue(),'ขก2302');assert.equal(await page.locator('#visitor-list .visit-row:visible').count(),1);assert(await page.locator('[data-action="visitor-status-clear"]').isDisabled());
 await page.getByLabel('ค้นหาทะเบียนรถ').fill('ไม่มีทะเบียน');await page.locator('[data-action="visitor-filter-reset"]').click();assert.equal(await page.getByLabel('ค้นหาทะเบียนรถ').inputValue(),'');assert.equal(await page.locator('[data-visitor-status]:checked').count(),0);assert(await page.locator('#visitor-filter-empty').isHidden());assert(await page.locator('#visitor-search-result').evaluate(el=>!!(el.compareDocumentPosition(document.querySelector('#visitor-list'))&Node.DOCUMENT_POSITION_FOLLOWING)));
 for(let i=0;i<ids.length;i++){
 await page.goto(base+'#visitors/registered');const card=page.locator('[data-id="'+ids[i]+'"]');assert.equal(await card.locator('.pill').innerText(),labels[i]);if(i===0)assert(await card.locator('.pill').evaluate(el=>el.classList.contains('blue')));
 assert.equal(await card.locator('.icon-button').count(),0);await card.locator('.visitor-row-open').click();await page.waitForURL('**/#estamp-reserve/'+ids[i]);await page.reload();assert.equal(await page.locator('.visitor-detail-actions .icon-button').count(),i===0?2:0);
 assert.equal(await page.locator('.booking-detail-summary .pill').innerText(),labels[i]);assert(await page.locator('.booking-qr-image').evaluate(img=>img.complete&&img.naturalWidth>0));
 assert.equal(await page.locator('form[data-form="visitor-stamp"]').count(),i===1?1:0);
 if(i===0)assert(await page.locator('.booking-detail-summary .pill').evaluate(el=>getComputedStyle(el).color==='rgb(39, 78, 129)'));
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 }
 await page.goto(base+'#estamp-reserve/PASS-001');assert.equal(await page.locator('.reserve-qr-number').innerText(),'PASS-001');
 const directDownload=page.waitForEvent('download');await page.getByRole('button',{name:'ดาวน์โหลด QR Code',exact:true}).click();assert.equal((await directDownload).suggestedFilename(),'reserve-PASS-001.png');
 await page.evaluate(()=>{navigator.canShare=()=>true;navigator.share=async data=>{window.shared={type:data.files[0].type,name:data.files[0].name,size:data.files[0].size};};});
 await page.getByRole('button',{name:'แชร์ QR Code',exact:true}).click();assert.equal(await page.evaluate(()=>window.shared.name),'reserve-PASS-001.png');assert.equal(await page.evaluate(()=>window.shared.type),'image/png');assert((await page.evaluate(()=>window.shared.size))>1000);
 await page.evaluate(()=>navigator.canShare=()=>false);await page.getByRole('button',{name:'แชร์ QR Code',exact:true}).click();const download=page.waitForEvent('download');await page.locator('#modal [data-action="download-reserve-qr"]').click();assert.equal((await download).suggestedFilename(),'reserve-PASS-001.png');await page.locator('#modal [data-action="close"]').click();
 await page.evaluate(()=>{navigator.canShare=()=>true;navigator.share=async()=>{throw new DOMException('Cancelled','AbortError');};});await page.getByRole('button',{name:'แชร์ QR Code',exact:true}).click();assert.equal(await page.locator('#modal:modal').count(),0);
 await page.goto(base+'#estamp-reserve/'+ids[1]);await page.locator('form [type="submit"]').click();assert.match(page.url(),/#estamp-reserve\//);assert.equal(await page.locator('.booking-detail-summary .pill').innerText(),'ประทับตราแล้ว');assert.equal(await page.locator('form[data-form="visitor-stamp"]').count(),0);await page.reload();assert.equal(await page.locator('form[data-form="visitor-stamp"]').count(),0);
 await page.goto(base+'#estamp-reserve/missing');assert.match(await page.locator('#app').innerText(),/ไม่พบรายการลงทะเบียน/);
 const pickDate=async date=>{for(let i=0;i<24;i++){const month=await page.evaluate(()=>visitorRangeDraft.month);if(month===date.slice(0,7))break;await page.locator('[data-action="visitor-range-month"][data-offset="'+(month<date.slice(0,7)?1:-1)+'"]').click();}await page.locator('[data-action="visitor-range-day"][data-date="'+date+'"]').click();};
 await page.goto(base+'#visitor-new');assert.equal(await page.locator('[name="entryTime"],input[type="date"],input[type="file"]').count(),0);assert.equal(await page.locator('[data-action="visitor-range-open"]').count(),1);const range=await page.evaluate(()=>({start:iso(1),end:iso(35)}));
 await page.locator('[data-action="visitor-range-open"]').click();assert.equal(await page.locator('[data-action="visitor-range-month"][data-offset="-1"]').isDisabled(),true);await pickDate(range.start);assert(await page.locator('[data-action="visitor-range-apply"]').isDisabled());await pickDate(range.end);await page.locator('[data-action="visitor-range-apply"]').click();
 const rangeText=await page.locator('[data-visitor-range-text]').innerText();await page.locator('[data-action="visitor-range-open"]').click();await pickDate(range.start);await page.locator('#modal [data-action="close"]').first().click();assert.equal(await page.locator('[data-visitor-range-text]').innerText(),rangeText);
 for(const width of [320,390]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 await page.locator('[name="plate"]').fill('ทด 4321');await page.locator('[name="province"]').click();await page.locator('[data-action="visitor-set-province"][data-value="กรุงเทพมหานคร"]').click();
 const beforeCreation=Date.now();await page.locator('form [type="submit"]').click();await page.waitForURL('**/#estamp-reserve/*');
 const record=await page.evaluate(()=>JSON.parse(localStorage.getItem('bannayuu.resident.v1')).visitors.find(v=>v.plate==='ทด 4321'));assert(Date.parse(record.createdAt)>=beforeCreation&&Date.parse(record.createdAt)<=Date.now());assert.equal(record.start,range.start);assert.equal(record.end,range.end);assert.equal(record.entryMode,'single');assert.equal(record.entryTime,undefined);
 assert.equal(new URL(page.url()).hash,'#estamp-reserve/'+record.id);assert.equal(await page.locator('.reserve-qr-number').innerText(),record.id);assert.equal(await page.locator('.reserve-identity h2').innerText(),record.plate);
 await page.goto(base+'#visitor/'+record.id+'/edit');assert.equal(await page.locator('[name="end"]').inputValue(),range.end);await page.locator('[data-action="visitor-range-open"]').click();await pickDate(range.start);await pickDate(range.start);await page.locator('[data-action="visitor-range-apply"]').click();await page.locator('form [type="submit"]').click();await page.waitForURL('**/#visitors/registered');
 assert.equal(await page.evaluate(id=>JSON.parse(localStorage.getItem('bannayuu.resident.v1')).visitors.find(v=>v.id===id).createdAt,record.id),record.createdAt);
 await page.goto(base+'#estamp-reserve/'+record.id);await page.reload();
 const value=label=>page.locator('.reserve-details .details').first().locator('span').filter({hasText:new RegExp('^'+label+'$')}).evaluate(el=>el.nextElementSibling.textContent);
 assert.equal(await value('เวลาที่ลงทะเบียน'),await page.evaluate(timestamp=>visitorEventTime(timestamp),record.createdAt));assert.equal(await value('เวลาเข้า'),'ยังไม่มีข้อมูล');assert.equal(await value('เวลาออก'),'ยังไม่มีข้อมูล');
 await page.goto(base+'#estamp-reserve/'+ids[2]);assert.notEqual(await value('เวลาเข้า'),'ยังไม่มีข้อมูล');assert.notEqual(await value('เวลาออก'),'ยังไม่มีข้อมูล');
 await page.goto(base+'#visitor/'+ids[2]+'/edit');await page.waitForURL('**/#estamp-reserve/'+ids[2]);assert.equal(await page.locator('form[data-form="visitor"]').count(),0);
 await page.goto(base+'#estamp-reserve/'+record.id);if(await page.locator('[data-action="guard-dismiss"]:visible').count())await page.locator('[data-action="guard-dismiss"]:visible').click();await page.locator('[title="แก้ไขการลงทะเบียน"]').click();await page.waitForURL('**/#visitor/'+record.id+'/edit');assert.equal(await page.locator('[name="plate"]').inputValue(),record.plate);
 await page.goto(base+'#estamp-reserve/'+record.id);await page.locator('[data-action="visitor-delete"]').click();await page.locator('#modal .actions [data-action="close"]').click();assert.equal(new URL(page.url()).hash,'#estamp-reserve/'+record.id);await page.locator('[data-action="visitor-delete"]').click();await page.locator('[data-action="visitor-delete-confirm"]').click();await page.waitForURL('**/#visitors/registered');const createdRow=page.locator('.visit-row[data-id="'+record.id+'"]');assert.equal(await createdRow.count(),0);await page.reload();assert.equal(await createdRow.count(),0);
 assert.deepEqual(errors,[]);console.log('PASS: five statuses, QR/share, filters, dates, pending-only edit/delete, confirmation and persistence');
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{await browser?.close();server.kill();});
