const {spawn}=require('node:child_process'),assert=require('node:assert/strict');const {chromium}=require('C:/Users/ouan-dev/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const server=spawn(process.execPath,['server.cjs'],{env:{...process.env,PORT:'4192'},windowsHide:true,stdio:'pipe'});let browser;
(async()=>{await new Promise((r,j)=>{server.stdout.once('data',r);server.once('error',j);server.once('exit',c=>j(Error('server '+c)))});browser=await chromium.launch();const p=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});const errors=[];p.on('pageerror',e=>errors.push(e.message));const base='http://localhost:4192/#';await p.goto(base+'household');await p.locator('#household-members-title').waitFor();assert.equal(await p.locator('[data-route="invite"],[data-action="join-member"],[data-action="member-menu"]').count(),0);assert.equal(await p.locator('.household-members .household-permission.granted').count(),1);assert.equal(await p.locator('.household-members .household-permission.not-granted').count(),1);assert.equal(await p.locator('[name="approvalRecipient"]:checked').inputValue(),'m1');
for(const width of [320,390,768]){await p.setViewportSize({width,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'.work/household-'+width+'.png',fullPage:true});}
assert.equal(await p.locator('.household-notification-link,[data-action="add-home"]').count(),0);
assert(await p.locator('#household-recipient-editor').isHidden());assert.equal(await p.locator('.household-my-approval.is-recipient').count(),1);
assert(await p.evaluate(()=>document.querySelector('#household-mode-title').compareDocumentPosition(document.querySelector('#household-recipient-title'))&Node.DOCUMENT_POSITION_FOLLOWING));
await p.locator('[data-action="household-recipient-edit"]').click();
await p.locator('[name="approvalRecipient"][value="m2"]').check();
await p.locator('[data-action="household-recipient-cancel"]').click();
assert.equal(await p.locator('[name="approvalRecipient"]:checked').inputValue(),'m1');
assert(await p.locator('#household-recipient-editor').isHidden());
await p.locator('[data-action="household-recipient-edit"]').click();
await p.locator('[name="approvalRecipient"][value="m2"]').check();await p.locator('[data-action="household-recipient-save"]').click();assert(await p.locator('#household-cooldown').isVisible());assert(await p.locator('[name="approvalRecipient"][value="m1"]').isDisabled());assert.equal(await p.locator('.household-recipient-badge').count(),1);await p.reload();assert.equal(await p.locator('[name="approvalRecipient"]:checked').inputValue(),'m2');assert(await p.locator('[name="approvalRecipient"][value="m1"]').isDisabled());assert.match(await p.evaluate(()=>saveApprovalRecipient('m1').error),/60/);
await p.evaluate(()=>{house().contactPolicy.recipientChangedAt=Date.now()-HOUSEHOLD_COOLDOWN_MS+3000;save();});assert.match(await p.evaluate(()=>saveApprovalRecipient('m1').error),/60/);await p.evaluate(()=>{house().contactPolicy.recipientChangedAt=Date.now()-HOUSEHOLD_COOLDOWN_MS;save();syncHouseholdControls();});assert(await p.locator('[name="approvalRecipient"][value="m1"]').isEnabled());await p.locator('[data-action="household-recipient-edit"]').click();await p.locator('[name="approvalRecipient"][value="m1"]').check();await p.locator('[data-action="household-recipient-save"]').click();assert.equal(await p.locator('[name="approvalRecipient"]:checked').inputValue(),'m1');
// Owner modes produce the corresponding simulated robot decision.
for(const [mode,status] of [['bypass','allow'],['dnd','deny'],['approve','ringing']]){await p.locator('[name="householdMode"][value="'+mode+'"]').check();await p.locator('[data-action="household-mode-save"]').click();assert.equal(await p.evaluate(()=>house().contactPolicy.mode),mode);assert.equal(await p.locator('#household-recipient-title,.household-my-approval').count(),mode==='approve'?2:0);assert.equal(await p.locator('.household-members .household-recipient-badge').count(),mode==='approve'?1:0);assert.equal(await p.locator('[data-action="household-recipient-edit"]').count(),mode==='approve'?1:0);assert.equal(await p.evaluate(()=>{delete state.guardCalls?.[house().id];return currentGuardCall().status;}),status);await p.goto(base+'guard-call');assert.equal(await p.locator('[data-action="guard-answer"]').count(),mode==='approve'?1:0);await p.goto(base+'household');}
// Non-owner cannot mutate household policy or stamp, but may be the approval recipient.
await p.evaluate(()=>{state.profile.memberIds[house().id]='m2';state.profile.name=house().members[1].name;save();renderHousehold();});assert.equal(await p.locator('[data-action="household-mode-save"],[data-action="household-recipient-save"]').count(),0);assert.match(await p.evaluate(()=>saveHouseholdMode('bypass').error),/เจ้าบ้าน/);assert.match(await p.evaluate(()=>saveApprovalRecipient('m2').error),/เจ้าบ้าน/);assert.equal(await p.evaluate(()=>memberCanStamp()),false);assert.equal(await p.locator('.household-my-approval.not-recipient').count(),1);assert.equal(await p.locator('.household-identity .household-permission').innerText(),'ไม่มีสิทธิ์ E-Stamp');await p.goto(base+'visitors');await p.goto(base+'visitor-stamp/VISIT-DEMO-1');assert.equal(await p.locator('form[data-form="visitor-stamp"]').count(),0);await p.goto(base+'guard-call');assert.equal(await p.locator('[data-action="guard-answer"],[data-action="guard-decision"]').count(),0);
await p.evaluate(()=>{house().contactPolicy.recipientId='m2';state.settings.appVersion=2;save();});await p.goto(base+'home');assert.equal(await p.locator('#guard-notification').count(),1);await p.locator('[data-action="guard-dismiss"]').click();assert.equal(await p.evaluate(()=>canReceiveApproval()),true);
// Independent notification defaults and recipient fan-out.
await p.goto(base+'settings/notifications');assert.equal(await p.locator('[data-personal-notification]:checked').count(),5);await p.locator('[data-personal-notification="parcel"]').uncheck();await p.reload();if(await p.locator('[data-action="guard-dismiss"]:visible').count())await p.locator('[data-action="guard-dismiss"]').click();assert.equal(await p.locator('[data-personal-notification="parcel"]').isChecked(),false);await p.evaluate(()=>{state.profile.memberIds[house().id]='m1';state.profile.name=house().members[0].name;save();renderSettings('notifications');});assert.equal(await p.locator('[data-personal-notification]:checked').count(),5);
await p.evaluate(()=>{notify('ทดสอบพัสดุ','ถึงทุกคนที่เปิดรับ','parcels');notify('ทดสอบบิล','ถึงสมาชิกทุกคน','bills');save();});assert.deepEqual(await p.evaluate(()=>state.notifications.find(n=>n.title==='ทดสอบพัสดุ').recipientKeys),['h1:m1']);assert.deepEqual(await p.evaluate(()=>state.notifications.find(n=>n.title==='ทดสอบบิล').recipientKeys),['h1:m1','h1:m2']);await p.goto(base+'notifications');await p.locator('[data-action="read-notifications"]').click();assert.equal(await p.evaluate(()=>personalUnreadCount()),0);
await p.evaluate(()=>{state.profile.memberIds[house().id]='m2';state.profile.name=house().members[1].name;save();renderNotifications();});assert.equal(await p.getByText('ทดสอบพัสดุ',{exact:true}).count(),0);assert.equal(await p.getByText('ทดสอบบิล',{exact:true}).count(),1);assert(await p.evaluate(()=>personalUnreadCount()>0));await p.goto(base+'settings');await p.locator('[data-action="clear-notifications"]').click();await p.locator('[data-action="confirm-clear-notifications"]').click();assert.equal(await p.evaluate(()=>personalNotifications().length),0);assert(await p.evaluate(()=>state.notifications.length>0));
await p.goto(base+'invite');assert.equal(await p.locator('[data-action="join-member"]').count(),0);assert.equal(await p.locator('[data-route="management"]').count(),1);// Two live tabs simulate separate members receiving the same household event.
const ctx=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});const ownerPage=await ctx.newPage(),residentPage=await ctx.newPage();await ownerPage.goto(base+'household');await residentPage.goto(base+'household');await residentPage.evaluate(()=>{state.profile.memberIds[house().id]='m2';state.profile.name=house().members[1].name;renderHousehold();});
await ownerPage.evaluate(()=>{commit(()=>notify('ประกาศร่วม','ทดสอบส่งทุกคน','announcements'));});await residentPage.waitForFunction(()=>state.notifications.some(n=>n.title==='ประกาศร่วม'));assert.equal(await residentPage.evaluate(()=>activeHouseMember().id),'m2');await residentPage.waitForFunction(()=>document.querySelector('#toast').textContent==='ประกาศร่วม');await residentPage.goto(base+'notifications');assert.equal(await residentPage.locator('#app').getByText('ประกาศร่วม',{exact:true}).count(),1);
await residentPage.goto(base+'settings/notifications');await residentPage.locator('[data-personal-notification="announcement"]').uncheck();await ownerPage.waitForFunction(()=>house().members[1].notificationPreferences.announcement===false);await ownerPage.evaluate(()=>{commit(()=>notify('ประกาศปิดรับ','ส่งเฉพาะคนเปิด','announcements'));});await residentPage.waitForFunction(()=>state.notifications.some(n=>n.title==='ประกาศปิดรับ'));assert.equal(await residentPage.evaluate(()=>personalNotifications().some(n=>n.title==='ประกาศปิดรับ')),false);assert(await ownerPage.evaluate(()=>personalNotifications().some(n=>n.title==='ประกาศปิดรับ')));await ctx.close();
assert.deepEqual(errors,[]);console.log('PASS: household roles, juristic E-Stamp display/enforcement, one recipient, persisted 60-minute lock/boundary, all modes, recipient-only calls, per-user notification settings/fan-out/read/clear, mobile layouts');})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{await browser?.close();server.kill()});
