const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
let chromium;
try{({chromium}=require('playwright'));}catch{({chromium}=require('C:/Users/ouan-dev/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
const server=spawn(process.execPath,['server.cjs'],{env:{...process.env,PORT:'4175'},stdio:'pipe',windowsHide:true});
let browser;
(async()=>{
 await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);});
 browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:390,height:844}});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const key='bannayuu.session.v1';
 await page.goto('http://localhost:4175/#settings');
 await page.locator('#login-form').waitFor();
 assert.equal(await page.locator('#navigation').isVisible(),false);
 await page.locator('[name=username]').fill('cit');await page.locator('[name=password]').fill('wrong');
 await page.locator('#login-form [type=submit]').click();
 assert.match(await page.locator('#login-error').innerText(),/ไม่ถูกต้อง/);
 assert.equal(await page.evaluate(k=>localStorage.getItem(k),key),null);
 await page.screenshot({path:'.work/login-390.png',fullPage:true});
 await page.locator('[name=password]').fill('cit12345');await page.locator('#login-form [type=submit]').click();
 await page.locator('[data-logout]').waitFor();
 const s=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);
 assert.equal(s.expiresAt-s.createdAt,86400000);assert.equal(s.password,undefined);
 await page.reload();await page.locator('[data-logout]').waitFor();
 assert.deepEqual(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key),s);
 const other=await context.newPage();await other.goto('http://localhost:4175/#home');
 await other.locator('#navigation button').first().waitFor();
 await page.locator('[data-logout]').click();await other.locator('#login-form').waitFor();
 await page.goBack();assert.equal(await page.locator('#navigation').isVisible(),false);
 await page.goto('http://localhost:4175/#home');
 await page.evaluate(k=>{localStorage.setItem(k,'{bad json');},key);await page.reload();await page.locator('#login-form').waitFor();
 await page.evaluate(k=>{const createdAt=Date.now()-86400000;localStorage.setItem(k,JSON.stringify({username:'cit',createdAt,expiresAt:createdAt+86400000}));},key);
 await page.reload();await page.locator('#login-form').waitFor();
 await page.evaluate(k=>{const createdAt=Date.now()-86400000+2000;localStorage.setItem(k,JSON.stringify({username:'cit',createdAt,expiresAt:createdAt+86400000}));},key);
 await page.reload();await page.locator('#navigation button').first().waitFor();await page.locator('#login-form').waitFor({timeout:5000});
 await page.setViewportSize({width:320,height:740});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:'.work/login-320.png',fullPage:true});
 assert.deepEqual(errors,[]);
 console.log('Login checks passed: credentials, persistence, fixed 24-hour expiry, live expiry, logout across tabs, invalid session, mobile layout.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();server.kill();});
