const {spawn}=require('node:child_process'),assert=require('node:assert/strict'),fs=require('node:fs');const {chromium}=require('C:/Users/ouan-dev/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const server=spawn(process.execPath,['server.cjs'],{env:{...process.env,PORT:'4198'},windowsHide:true,stdio:'pipe'});let browser;
(async()=>{await new Promise(r=>server.stdout.once('data',r));browser=await chromium.launch();const p=await browser.newPage({viewport:{width:390,height:844}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:4198/#visitors/registered');await p.goto('http://localhost:4198/#estamp-reserve/PASS-001');await p.locator('[data-action="guard-dismiss"]').click();fs.mkdirSync('.work/reserve-polish',{recursive:true});
 for(const width of [320,390,768]){await p.setViewportSize({width,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'.work/reserve-polish/front-'+width+'.png',fullPage:true});}
 const details=p.locator('[data-side="details"]');await details.focus();await p.keyboard.press('Enter');assert.equal(await details.getAttribute('aria-pressed'),'true');assert(await p.locator('.reserve-pass-front').evaluate(e=>e.inert));assert.equal(await p.locator('.reserve-info-group').count(),3);await p.setViewportSize({width:390,height:844});await p.waitForTimeout(500);await p.screenshot({path:'.work/reserve-polish/back.png',fullPage:true});
 const download=p.waitForEvent('download');await p.locator('[data-action="download-reserve-qr"]').click();await download;assert.equal(await details.getAttribute('aria-pressed'),'true');await p.evaluate(()=>{navigator.canShare=()=>true;navigator.share=async()=>{window.shared=true;};});await p.locator('[data-action="share-reserve-qr"]').click();await p.waitForFunction(()=>window.shared);assert.equal(await details.getAttribute('aria-pressed'),'true');
 await p.locator('.reserve-pass-title').click();assert.equal(await p.locator('[data-side="qr"]').getAttribute('aria-pressed'),'true');assert.equal(await p.locator('.header [data-action="visitor-cancel"]:visible').count(),0);await p.locator('.reserve-more summary').click();await p.locator('[data-action="visitor-cancel"]').click();assert(await p.locator('#modal').isVisible());await p.locator('#modal [data-action="close"]').first().click();
 await p.locator('[data-action="visitor-cancel"]').click();await p.locator('[data-action="visitor-cancel-confirm"]').click();assert.equal(await p.locator('.reserve-status').innerText(),'ยกเลิก');assert.equal(await p.locator('.reserve-more').count(),0);assert(await p.evaluate(()=>{const v=JSON.parse(localStorage.getItem('bannayuu.resident.v1')).visitors.find(v=>v.id==='PASS-001');return v.revoked&&!!v.cancelledAt;}));
 const pending=await p.evaluate(()=>{const v=scoped(state.visitors).find(v=>canStampVisitor(v)&&v.source!=='walkin');return v.id;});await p.goto('http://localhost:4198/#estamp-reserve/'+pending);assert.equal(await p.locator('form[data-form="visitor-stamp"]').count(),1);assert.equal(await p.locator('.reserve-more').count(),0);assert.equal((await p.locator('.reserve-usage strong').innerText()).includes(' – '),false);
 assert.deepEqual(errors,[]);console.log('PASS: responsive layout, keyboard/card switch, shared actions on back, cancellation confirmation and retained history, eligibility, single-day date');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{await browser?.close();server.kill()});
