const assert=require('node:assert/strict'),{spawn}=require('node:child_process');
let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require('C:/Users/ouan-dev/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
const server=spawn(process.execPath,['server.cjs'],{env:{...process.env,PORT:'4194'},windowsHide:true,stdio:'pipe'});let browser;
(async()=>{
 await new Promise((ok,no)=>{server.stdout.once('data',ok);server.stderr.once('data',d=>no(Error(d)));});browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:4194/#visitors/registered');
 const dismiss=async()=>{if(await page.locator('[data-action="guard-dismiss"]').count())await page.locator('[data-action="guard-dismiss"]').click();};await dismiss();assert.equal(await page.getByRole('button',{name:'สแกน QR Code',exact:true}).count(),0);await page.goto('http://localhost:4194/#scan/registered');await page.waitForURL('**/#scan/registered');assert(await page.locator('#scan-picker-title').isVisible());
 await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('Denied','NotAllowedError');};});await page.locator('[data-action="scan-camera"]').click();await page.waitForFunction(()=>document.querySelector('#visitor-qr-message').textContent.includes('ไม่ได้รับอนุญาต'));await page.getByRole('button',{name:'ปิดกล้องและเลือกรายการ'}).click();
 await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{const c=document.createElement('canvas');c.width=c.height=480;const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,480,480);window.testCameraCanvas=c;window.testCameraStream=c.captureStream(10);return window.testCameraStream;};});await page.locator('[data-action="scan-camera"]').click();await page.waitForFunction(()=>document.querySelector('#visitor-qr-message').textContent==='พร้อมสแกน QR Code');assert(await page.locator('#visitor-qr-video').isVisible());await page.getByRole('button',{name:'ปิดกล้องและเลือกรายการ'}).click();assert(await page.evaluate(()=>testCameraStream.getTracks().every(t=>t.readyState==='ended')));
 await page.locator('[data-action="scan-camera"]').click();await page.waitForFunction(()=>document.querySelector('#visitor-qr-message').textContent==='พร้อมสแกน QR Code');await page.evaluate(()=>{const qr=reservationQrImage('BANNAYUU-DEMO-RESERVE:PASS-001',true);window.testDrawTimer=setInterval(()=>testCameraCanvas.getContext('2d').drawImage(qr,40,40,400,400),100);});await page.waitForURL('**/#estamp-reserve/PASS-001');assert(await page.evaluate(()=>testCameraStream.getTracks().every(t=>t.readyState==='ended')));assert.equal(await page.locator('form[data-form="visitor-stamp"]').count(),0);
 assert.equal(await page.evaluate(()=>readVisitorQr('https://invalid.example/')),false);assert.equal(await page.evaluate(()=>readVisitorQr('BANNAYUU-DEMO-RESERVE:UNKNOWN')),false);
 await page.goto('http://localhost:4194/#scan/registered');await page.setViewportSize({width:320,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('PASS: reserve navigation, denied camera, live preview, close cleanup, actual branded QR decoding and review routing, invalid QR, mobile layout');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();server.kill();});
