const assert=require('node:assert/strict'),{spawn}=require('node:child_process'),fs=require('node:fs');
let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require('C:/Users/ouan-dev/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
const server=spawn(process.execPath,['server.cjs'],{env:{...process.env,PORT:'4193'},windowsHide:true,stdio:'pipe'});let browser;
(async()=>{
 await new Promise((ok,no)=>{server.stdout.once('data',ok);server.stderr.once('data',d=>no(Error(d)));});browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:4193/#scan');const dismiss=async()=>{if(await page.locator('[data-action="guard-dismiss"]').count())await page.locator('[data-action="guard-dismiss"]').click();};await dismiss();
 assert(await page.locator('.scan-visitor').count()>0);
 await page.evaluate(()=>{const key='bannayuu.resident.v1',s=JSON.parse(localStorage.getItem(key)),v=s.visitors.find(v=>v.source==='walkin'&&!v.stamped&&!v.revoked);s.visitors.push({...v,id:'SCAN-TEST',name:'ผู้มาติดต่อทดสอบชื่อยาวสำหรับตรวจการจัดวางบนหน้าจอมือถือ',plate:'กข 9988'}, {...v,id:'SCAN-EXITED',exitedAt:new Date().toISOString()});localStorage.setItem(key,JSON.stringify(s));});await page.reload();await dismiss();
 assert.equal(await page.locator('[data-id="SCAN-EXITED"]').count(),0);
 const search=page.locator('#scan-search');await search.fill('กข9988');assert.equal(await page.locator('.scan-visitor:visible').count(),1);await search.fill('ไม่พบแน่นอน');assert(await page.locator('#scan-no-results').isVisible());await page.locator('[data-action="scan-search-clear"]').click();assert.equal(await search.inputValue(),'');assert(await search.evaluate(el=>el===document.activeElement));
 fs.mkdirSync('.work/scan-layout',{recursive:true});for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`.work/scan-layout/${width}.png`,fullPage:true});}
 await search.fill('กข9988');await page.locator('[data-id="SCAN-TEST"]').focus();await page.keyboard.press('Enter');await page.waitForURL('**/#visitor-stamp/SCAN-TEST');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('bannayuu.resident.v1')).visitors.find(v=>v.id==='SCAN-TEST').stamped),false);
 await page.evaluate(()=>{const key='bannayuu.resident.v1',s=JSON.parse(localStorage.getItem(key));s.visitors.forEach(v=>v.stamped=true);localStorage.setItem(key,JSON.stringify(s));});await page.goto('http://localhost:4193/#scan');await page.reload();assert.equal(await page.locator('.scan-visitor').count(),0);assert(await page.getByText('ไม่มีผู้มาติดต่อรอประทับตรา',{exact:true}).isVisible());assert.deepEqual(errors,[]);console.log('PASS: search, no results/reset, eligibility, keyboard review without stamping, responsive widths, empty state');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();server.kill();});
