const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
let chromium;
try { ({chromium} = require('playwright')); }
catch { ({chromium} = require('C:/Users/ouan-dev/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')); }
const { spawn } = require('node:child_process');
const server = spawn(process.execPath, ['server.cjs'], { cwd: path.resolve(__dirname, '..'), env: {...process.env, PORT: '4174'}, stdio: 'pipe', windowsHide: true });
const results = [];
const root = path.resolve(__dirname, '..');
let activeBrowser;
async function main() {
 await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.once('exit',code=>reject(Error('Test server exited '+code)));});
 const browser=activeBrowser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,reducedMotion:'reduce'});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('bannayuu.resident.v1')));
 const go=async route=>{await page.goto('http://localhost:4174/#'+route);await page.locator('#app .route-fade').waitFor();};
 const fill=async(name,value)=>page.locator(`[name="${name}"]`).fill(value);
 const choose=async(name,value)=>page.locator(`[name="${name}"]`).selectOption(value);
 const submit=async()=>{await page.locator('form [type=submit]').click();await page.waitForTimeout(120);};
 const click=async(action)=>page.locator(`[data-action="${action}"]`).first().click();
 const today=new Date().toISOString().slice(0,10);
 fs.mkdirSync(path.join(root,'.work/app'),{recursive:true});
 await page.goto('http://localhost:4174/#home');
 await fill('username','cit');await fill('password','cit12345');
 await page.locator('#login-form [type=submit]').click();
 await go('home');await page.screenshot({path:path.join(root,'.work/app/home-mobile.png'),fullPage:true});
 assert.equal(await page.locator('#navigation button').count(),6);
 assert.equal(await page.locator('.menu-grid button').count(),16);
 results.push('Home: 16 shortcuts and 6 navigation tabs');
 await go('payment/BILL-001');await submit();assert.equal((await read()).bills[0].paid,false);await click('promptpay-complete');await page.waitForURL(/receipt/);assert((await read()).bills[0].paid);await page.reload();assert.match(await page.locator('#app').innerText(),/ชำระเงินสำเร็จ/);results.push('Payment persists and receipt renders after reload');
 const receiptDownload=page.waitForEvent('download');await click('download-receipt');assert((await receiptDownload).suggestedFilename().endsWith('.html'));
 await go('parcel/PCL-001');await click('receive-parcel');await click('confirm-parcel');assert((await read()).parcels[0].received);results.push('Parcel receipt and history');
 await go('facility/F1');await choose('time','09:00–10:00');await page.locator('[name=agree]').check();await submit();assert.equal((await read()).bookings.length,1);
 await go('facility/F1');await choose('time','09:00–10:00');await page.locator('[name=agree]').check();await submit();assert.equal((await read()).bookings.length,1);assert.match(await page.locator('#toast').innerText(),/ถูกจอง/);
 await go('facilities/bookings');await click('cancel-booking');await click('confirm-cancel-booking');assert.equal((await read()).bookings[0].status,'ยกเลิกแล้ว');results.push('Facility booking, conflict detection and cancellation');
 await go('household');await click('member-menu');await choose('role','ผู้เช่า');await submit();assert.equal((await read()).homes[0].members[0].role,'ผู้เช่า');
 await go('invite');await click('join-member');await fill('name','สมาชิก ทดสอบ');await submit();assert.equal((await read()).homes[0].members.length,3);results.push('Household roles and joining with invite code');
 await go('vehicles');await click('new-vehicle');await page.waitForURL(/vehicle-new/);await choose('kind','รถยนต์');await choose('engine','ไฟฟ้า/ปลั๊กอินไฮบริด');await fill('plate','กท 9999');await choose('province','กรุงเทพมหานคร');await submit();await fill('brand','Toyota');await fill('model','Test');await fill('color','ขาว');await submit();await page.locator('[name=agree]').check();await submit();assert.equal((await read()).vehicles.length,1);results.push('Three-step vehicle registration');
 await go('pets');for(let i=0;i<3;i++)await click('pet-intro');await go('pet-new');
 const tinyPng=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64');
 await page.locator('input[type=file]').setInputFiles({name:'pet.png',mimeType:'image/png',buffer:tinyPng});await page.waitForFunction(()=>document.querySelector('#photo-preview img'));
 await fill('thai','มะลิ');await fill('english','Mali');await choose('species','แมว');await fill('breed','ไทย');await fill('birth','2023-01-01');await fill('weight','4.2');await choose('sex','เมีย');await fill('color','ขาว');await submit();await page.waitForTimeout(100);assert.equal((await read()).pets.length,1);await click('close');
 const petDownload=page.waitForEvent('download');await click('download-pet');assert((await petDownload).suggestedFilename().endsWith('.png'));await page.screenshot({path:path.join(root,'.work/app/pet-mobile.png'),fullPage:true});
 let pet=(await read()).pets[0];await go('pet/'+pet.id+'/edit');await fill('weight','4.5');await submit();await page.waitForTimeout(100);assert.equal((await read()).pets[0].weight,'4.5');await click('close');results.push('Pet onboarding, photo upload, create/edit and PNG export');
 await go('visitor-new');await fill('name','ช่าง ทดสอบ');await choose('category','รถยนต์');await fill('plate','1กข 2222');await submit();assert.equal((await read()).visitors.length,3);let visitor=(await read()).visitors[0];
 const passDownload=page.waitForEvent('download');await click('download-pass');assert((await passDownload).suggestedFilename().endsWith('-front.png'));await click('flip-pass');const backDownload=page.waitForEvent('download');await click('download-pass');assert((await backDownload).suggestedFilename().endsWith('-back.png'));
 await go('scan');await choose('pass',visitor.id);await submit();assert((await read()).visitors[0].stamped);results.push('Visitor registration, both i-Pass image sides and simulated E-Stamp');
 await go('feedback');await fill('title','ไฟสวนไม่ติด');await fill('detail','ใกล้ซอย 3');await submit();assert.equal((await read()).feedback.length,1);
 await go('repairs');await choose('type','ไฟฟ้า');await fill('location','สวน');await fill('detail','ไฟดับ');await submit();await click('repair-done');assert.equal((await read()).repairs[0].status,'เสร็จสิ้น');results.push('Feedback and repair lifecycle');
 await go('chat');await fill('text','สวัสดี');await submit();assert.equal((await read()).chat.length,3);
 await go('vote');await page.locator('[value="เห็นชอบ"]').check();await submit();await click('confirm-vote');assert.equal((await read()).votes.h1,'เห็นชอบ');
 await go('benefits');await click('redeem');await click('confirm-redeem');assert.equal((await read()).redeemed.length,1);results.push('Mock chat, vote and benefit redemption');
 await go('announcement/A1');await click('acknowledge');assert((await read()).announcements[0].read);
 await go('service/S1/book');await choose('time','09:00–12:00');await submit();assert.equal((await read()).serviceBookings[0].total,649);await click('cancel-service');await click('confirm-cancel-service');assert.equal((await read()).serviceBookings[0].status,'ยกเลิกแล้ว');results.push('Announcement acknowledgment and partner service booking/cancel');
 await go('timeline');await click('new-post');await fill('text','ทดสอบโพสต์ <script>alert(1)</script>');await submit();assert.equal((await read()).posts.length,3);await click('like');await click('comment');await fill('text','ยินดีค่ะ');await submit();assert.equal((await read()).posts[0].comments.length,1);assert.equal(await page.locator('#app script').count(),0);results.push('Timeline post, like, comment and HTML escaping');
 await go('product/KUMA');await click('product-sheet');await click('sheet-quantity');await click('add-cart');await go('cart');assert(await page.locator('[data-route=checkout]').isDisabled());await page.locator('#select-all').check();await page.locator('[data-route=checkout]').click();await submit();assert.equal((await read()).orders.length,1);assert.equal((await read()).orders[0].total,180);assert.equal((await read()).cart.length,0);await click('order-received');assert.equal((await read()).orders[0].status,'ได้รับสินค้าแล้ว');results.push('Cart selection, totals including shipping, checkout and received state');
 await go('settings/profile');await fill('name','ผู้ใช้ ทดสอบ');await submit();assert.equal((await read()).profile.name,'ผู้ใช้ ทดสอบ');
 await go('home');await click('switch-home');await click('add-home');await fill('number','212/2');await submit();await go('bills');assert.match(await page.locator('#app').innerText(),/ไม่มีรายการในแจ้งหนี้/);await go('vehicles');assert.match(await page.locator('#app').innerText(),/ไม่มีรายการยานพาหนะ/);results.push('Profile and isolation between houses');
 await go('settings/demo');await page.locator('[data-setting=servicesEnabled]').uncheck();await go('repairs');assert.match(await page.locator('#app').innerText(),/ฟีเจอร์นี้ยังไม่เปิด/);await go('settings/demo');await page.locator('[data-setting=emptyMode]').check();await go('announcements');assert.match(await page.locator('#app').innerText(),/ยังไม่มีประกาศสำคัญ/);results.push('Demo toggles for disabled services and manual empty states');
 await go('settings/language');await choose('language','English');await submit();assert.match(await page.locator('#navigation').innerText(),/Home/);results.push('English navigation preference');
 const routes=['home','bills','bills/paid','bills/deposit','parcels','parcels/history','facilities','facilities/bookings','household','invite','vehicles','pets','visitors','visitors/registered','visitors/coupons','scan','feedback','feedback/history','phone','phone/emergency','phone/other','management','repairs','emergency','chat','rules','benefits','vote','announcements','announcements/general','services','services/bookings','timeline','shopping','product/KUMA','cart','orders','settings','settings/profile','settings/notifications','settings/language','settings/camera','settings/marketing','settings/privacy','settings/terms','settings/developer','settings/demo','settings/about','notifications','help'];
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:900});for(const r of routes){await go(r);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert(!overflow,`Horizontal overflow at ${width}: ${r}`);assert(await page.locator('#app').innerText(),`Empty route ${r}`);} }
 results.push('50 routes checked at 320px, 390px and 1440px without horizontal overflow');
 await page.setViewportSize({width:1440,height:1000});await go('settings/demo');await click('reset-ask');await click('reset-confirm');await page.waitForURL(/#home/);assert.equal((await read()).homes.length,1);assert.equal((await read()).pets.length,0);assert.equal((await read()).orders.length,0);assert.equal((await read()).bills[0].paid,false);await page.screenshot({path:path.join(root,'.work/app/home-desktop.png'),fullPage:true});
 results.push('Reset restores initial sample data');
 assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(root,'.work/app/verification.json'),JSON.stringify({passed:results,errors},null,2));
 console.log(JSON.stringify({passed:results,errors},null,2));
 await browser.close();
}
main().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{await activeBrowser?.close();server.kill();});
