#!/usr/bin/env node
/**
 * tokens.mjs — generate src/app/tokens.css from the DESIGN.md frontmatter.
 *
 *   node scripts/tokens.mjs
 *
 * DESIGN.md is the single source of truth for colour, type and spacing.
 * Hand-copying those values into CSS is how a design system drifts: the doc
 * says one thing, the build ships another, and nobody notices for months.
 * So the CSS is generated, and tokens.css is never edited by hand.
 *
 * The parser handles exactly the subset of YAML this frontmatter uses —
 * two levels of mapping, scalar leaves, no lists, no anchors. It is not a
 * YAML implementation and should not grow into one; if the frontmatter ever
 * needs more, add a real parser as a dependency instead.
 */

import { readFileSync, writeFileSync } from 'node:fs';

const src = readFileSync('DESIGN.md', 'utf8');
const m = src.match(/^---\r?\n([\s\S]*?)\r?\n---/);
if (!m) {
  console.error('DESIGN.md has no YAML frontmatter.');
  process.exit(1);
}

/** Parse the restricted subset: two levels of `key: value` by indentation. */
function parse(text) {
  const root = {};
  let section = null;
  let sub = null;

  for (const raw of text.split(/\r?\n/)) {
    if (!raw.trim() || raw.trimStart().startsWith('#')) continue;
    const indent = raw.length - raw.trimStart().length;
    const line = raw.trim();
    const idx = line.indexOf(':');
    if (idx === -1) continue;

    const key = line.slice(0, idx).trim();
    let value = line.slice(idx + 1).trim();
    if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);

    if (indent === 0) {
      section = value === '' ? (root[key] = {}) : ((root[key] = value), null);
      sub = null;
    } else if (indent === 2 && section) {
      sub = value === '' ? (section[key] = {}) : ((section[key] = value), null);
    } else if (indent >= 4 && sub) {
      sub[key] = value;
    }
  }
  return root;
}

const fm = parse(m[1]);

/** {colors.page} -> var(--color-page) */
const deref = (v) =>
  String(v).replace(/\{([a-z]+)\.([a-zA-Z0-9-]+)\}/g, (_, group, key) => {
    const prefix = { colors: 'color', rounded: 'radius', spacing: 'space', typography: 'type' }[group] ?? group;
    return `var(--${prefix}-${key})`;
  });

const out = [];
out.push('/* GENERATED by scripts/tokens.mjs from DESIGN.md — do not edit. */');
out.push('/* Run `node scripts/tokens.mjs` after changing the DESIGN.md frontmatter. */');
out.push('');
out.push(':root {');

for (const [k, v] of Object.entries(fm.colors ?? {})) out.push(`  --color-${k}: ${v};`);
out.push('');
for (const [k, v] of Object.entries(fm.rounded ?? {})) out.push(`  --radius-${k}: ${v};`);
out.push('');
for (const [k, v] of Object.entries(fm.spacing ?? {})) out.push(`  --space-${k}: ${v};`);
out.push('');

for (const [role, props] of Object.entries(fm.typography ?? {})) {
  if (typeof props !== 'object') continue;
  const map = {
    fontFamily: 'family', fontSize: 'size', fontWeight: 'weight',
    lineHeight: 'leading', letterSpacing: 'tracking', fontFeature: 'feature',
  };
  for (const [p, val] of Object.entries(props)) {
    const suffix = map[p];
    if (suffix) out.push(`  --type-${role}-${suffix}: ${val};`);
  }
}
out.push('}');
out.push('');

// Components become utility classes rather than more variables: a component
// token that nothing consumes is documentation pretending to be code.
for (const [name, props] of Object.entries(fm.components ?? {})) {
  if (typeof props !== 'object') continue;
  const decls = [];
  const css = {
    backgroundColor: 'background-color', textColor: 'color', rounded: 'border-radius',
    padding: 'padding', height: 'height', width: 'width', size: 'font-size',
  };
  for (const [p, val] of Object.entries(props)) {
    if (p === 'typography') {
      const role = String(val).replace(/[{}]/g, '').split('.')[1];
      decls.push(`  font-family: var(--type-${role}-family);`);
      decls.push(`  font-size: var(--type-${role}-size);`);
      decls.push(`  font-weight: var(--type-${role}-weight);`);
      continue;
    }
    if (css[p]) decls.push(`  ${css[p]}: ${deref(val)};`);
  }
  if (decls.length) out.push(`.fb-${name} {`, ...decls, '}', '');
}

writeFileSync('src/app/tokens.css', out.join('\n'), 'utf8');
console.log(`Wrote src/app/tokens.css — ${Object.keys(fm.colors ?? {}).length} colours, ` +
            `${Object.keys(fm.typography ?? {}).length} type roles, ` +
            `${Object.keys(fm.components ?? {}).length} component classes.`);
